### ISSUE TITLE
Index error on make_animator()

### ISSUE THREAD

**Issue by cobanov** [Sohl-Dickstein/fractal#1]
Hello,

I'm facing this issue when I run the colab notebook

```python
ts = 30
anim = make_animator(hist_video, timesteps_per_transition=ts*2)
anim.save(f'/content/drive/MyDrive/fractal/{canonical_name()}.mp4',fps=ts, dpi=dpi)
plt.close('all')
```

```
IndexError                                Traceback (most recent call last)

[<ipython-input-43-f9d8f3393ede>](https://localhost:8080/#) in <cell line: 2>()
      1 ts = 30
----> 2 anim = make_animator(hist_video, timesteps_per_transition=ts*2)
      3 anim.save(f'/content/drive/MyDrive/fractal/{canonical_name()}.mp4',fps=ts, dpi=dpi)
      4 plt.close('all')

[<ipython-input-38-a74898fefe2e>](https://localhost:8080/#) in make_animator(history, timesteps_per_transition, reference_scale, cmap)
     39 
     40   im2 = ax.imshow(
---> 41       jnp.zeros_like(history[1][0]), extent=em(history[1][1]), origin='lower',
     42       vmin = -1, vmax = 1,
     43       cmap=cmap,

IndexError: list index out of range
```

**Comment by Sohl-Dickstein** [comment]
My best guess is that you should zoom farther in the interactive exploration cell a couple cells earlier. `image_history` records the sequence of regions you've looked at interactively. `hist_video` will then hold a sequence of frames zooming into your most recent location. Then the animation will animate that zoom sequence. But for that to work, you need to have zoomed in far enough in the earlier cell, that the last entry in image_history is zoomed in by several powers of 2 compared to where it was at initialization.

**Comment by cobanov** [comment]
Thank you very much for your answer, but what I am trying to understand is that when I run the notebook as is without making any changes, I get this error. Could it be due to an update coming to the packages?

**Comment by Sohl-Dickstein** [comment]
You need to interactively explore the fractal in the interactive
exploration cell from a few cells earlier. You shouldn't run the next cells
until after you've done that.
